- hosts: all
  tasks:
    - name: Install ruby
      become: yes
      yum: name=ruby state=present
      


    - name: Install sinatra
      gem:
        name: sinatra
        version: 1.4.8
        state: present

    - name: Create service template
      become: yes
      template:
        src: web.rb.service.j2
        dest: /etc/systemd/system/ruby.service

    - name: copy artifact
      copy:
        src: web.rb
        backup: yes
        force: yes
        dest: /home/vagrant/web.rb
        mode: '0777'
    
    - name: enable and start service
      become: yes
      systemd:
        name: web.rb
        enabled: yes
        state: restarted
